### ISSUE TITLE
Restify main example failing on "restify": "^4.1.1"

### ISSUE THREAD

**Issue by eugeniol** [restify/node-restify#1144]
Using node v6.2.0 I installed latest version of "restify": "^4.1.1"

When i try to run example

	var restify = require('restify');

	function respond(req, res, next) {
	  res.send('hello ' + req.params.name);
	  next();
	}

	var server = restify.createServer();
	server.get('/hello/:name', respond);
	server.head('/hello/:name', respond);

	server.listen(8080, function() {
	  console.log('%s listening at %s', server.name, server.url);
	});

It fails with 

	/Users/uke/dev/sm-apidocs/node_modules/restify/lib/server.js:490
	                if (this.app.mounts[opts.name]) { // GH-401
	                            ^

	TypeError: Cannot read property 'mounts' of undefined
	    at Server.(anonymous function) [as get] (/Users/uke/dev/sm-apidocs/node_modules/restify/lib/server.js:490:29)
	    at Object.<anonymous> (/Users/uke/dev/sm-apidocs/server/demo.js:9:8)
	    at Module._compile (module.js:541:32)
	    at Object.Module._extensions..js (module.js:550:10)
	    at Module.load (module.js:458:32)
	    at tryModuleLoad (module.js:417:12)
	    at Function.Module._load (module.js:409:3)
	    at Function.Module.runMain (module.js:575:10)
	    at startup (node.js:160:18)
	    at node.js:449:3

If i downgrade restify to 4.0.4 it works without issues

**Comment by DonutEspresso** [comment]
I tried to repro this using node 6.2.2 and 4.1.1, but the server started up without any issues. Can you share more about your environment and how you're starting up the process?

**Comment by eugeniol** [comment]
Hey @DonutEspresso thanks for replying, i've just tried again and it works, maybe was something weird on my mac env. I will close this issue.
