### ISSUE TITLE
Internal server error not handled on using formatters

### ISSUE THREAD

**Issue by suhas-karanth** [restify/node-restify#1169]
My restify server config:
```
   {
        name: 'MyHttpApi',
        log: require('../logger'), // Pass our logger to restify.
        formatters: {
            'application/json': formatJSON
        }
    }
```
I am reusing the formatter which ships with restify with only slight modification
<details>
  <summary>json formatter code</summary>
  ```
'use strict';

/* eslint-disable no-param-reassign */

/**
 * JSON formatter.
 * @public
 * @function formatJSON
 * @param    {Object} req  the request object
 * @param    {Object} res  the response object
 * @param    {Object} body response body
 * @param    {Function} cb cb
 * @returns  {String}
 */
module.exports = function formatJSON(req, res, body, cb) {
    if (body instanceof Error) {
        // snoop for RestError or HttpError, but don't rely on
        // instanceof
        res.statusCode = body.statusCode || 500;

        if (body.body) {
            body = body.body;
        } else {
            body = {
                message: body.message
            };
        }
    } else if (Buffer.isBuffer(body)) {
        body = body.toString('base64');
    }

    let data;
    if (req.query && req.query.hasOwnProperty('pretty')) {
        data = JSON.stringify(body, null, 2);
    } else {
        data = JSON.stringify(body);
    }

    res.setHeader('Content-Length', Buffer.byteLength(data));

    return cb(null, data);
};
```
</details>

<details>
 <summary>Stack trace with new formatter on internal server error</summary>
```
[2016-08-20T04:02:25.884Z] ERROR: my/18056 on suhas-VirtualBox (/home/suhas/workspace/my_http_api/src/resources/v1/score.js:163 in score): params.hasOwnProperty is not a function (req_id=49946335-64a3-4313-a205-0b35dc5a25b0)
    TypeError: params.hasOwnProperty is not a function
        at Object.surveyDetails (/home/suhas/workspace/my_http_api/src/substratum/es_client.js:201:16)
        at score (/home/suhas/workspace/my_http_api/src/resources/v1/score.js:138:48)
        at next (native)
        at Server.asyncFunc (/home/suhas/workspace/my_http_api/src/substratum/util.js:216:37)
        at next (/home/suhas/workspace/my_http_api/node_modules/restify/lib/server.js:906:30)
        at f (/home/suhas/workspace/my_http_api/node_modules/once/once.js:17:25)
        at Server.bunyan (/home/suhas/workspace/my_http_api/node_modules/restify/lib/plugins/bunyan.js:58:9)
        at next (/home/suhas/workspace/my_http_api/node_modules/restify/lib/server.js:906:30)
        at f (/home/suhas/workspace/my_http_api/node_modules/once/once.js:17:25)
        at Server.gzip (/home/suhas/workspace/my_http_api/node_modules/restify/lib/plugins/gzip.js:30:13)
        at next (/home/suhas/workspace/my_http_api/node_modules/restify/lib/server.js:906:30)
        at f (/home/suhas/workspace/my_http_api/node_modules/once/once.js:17:25)
        at Server.parseBody (/home/suhas/workspace/my_http_api/node_modules/restify/lib/plugins/body_parser.js:52:17)
        at next (/home/suhas/workspace/my_http_api/node_modules/restify/lib/server.js:906:30)
        at f (/home/suhas/workspace/my_http_api/node_modules/once/once.js:17:25)
        at Server.readBody (/home/suhas/workspace/my_http_api/node_modules/restify/lib/plugins/body_reader.js:74:13)
Unhandled rejection TypeError: req.query.hasOwnProperty is not a function
    at ServerResponse.formatJSON (/home/suhas/workspace/my_http_api/src/substratum/bones/json_formatter.js:33:32)
    at ServerResponse.format (/home/suhas/workspace/my_http_api/node_modules/restify/lib/response.js:152:23)
    at ServerResponse.send (/home/suhas/workspace/my_http_api/node_modules/restify/lib/response.js:340:14)
    at next (/home/suhas/workspace/my_http_api/node_modules/restify/lib/server.js:840:25)
    at f (/home/suhas/workspace/my_http_api/node_modules/once/once.js:17:25)
    at score (/home/suhas/workspace/my_http_api/src/resources/v1/score.js:164:16)
    at next (native)
    at Server.asyncFunc (/home/suhas/workspace/my_http_api/src/substratum/util.js:216:37)
    at next (/home/suhas/workspace/my_http_api/node_modules/restify/lib/server.js:906:30)
    at f (/home/suhas/workspace/my_http_api/node_modules/once/once.js:17:25)
    at Server.bunyan (/home/suhas/workspace/my_http_api/node_modules/restify/lib/plugins/bunyan.js:58:9)
    at next (/home/suhas/workspace/my_http_api/node_modules/restify/lib/server.js:906:30)
    at f (/home/suhas/workspace/my_http_api/node_modules/once/once.js:17:25)
    at Server.gzip (/home/suhas/workspace/my_http_api/node_modules/restify/lib/plugins/gzip.js:30:13)
    at next (/home/suhas/workspace/my_http_api/node_modules/restify/lib/server.js:906:30)
    at f (/home/suhas/workspace/my_http_api/node_modules/once/once.js:17:25)
```
</details>

The cURL
```
curl -X GET -H "Authorization: Basic dGVzdDo=" -H "Cache-Control: no-cache" "http://localhost:3000/v1/score?start_date=2016-08-16&end_date=2016-08-17"
curl: (52) Empty reply from server
```
I have created a separate [issue](https://github.com/restify/node-restify/issues/1168) for `req.query.hasOwnProperty` not a function error.

When I don't use the formatter, the response:
```
{"message":"params.hasOwnProperty is not a function"}
```

**Comment by DonutEspresso** [comment]
Hello, it would be helpful to know how the `TypeError: params.hasOwnProperty is not a function` error in es_client.js is being propagated to restify. Is it via `next()`, or through the uncaughtException handler?

**Comment by suhas-karanth** [comment]
`es_client.js` returns a promise like so:
```
    // client is an elasticsearch client object. Calling search returns a promise
    return client.search({
        index: SURVEYS_READ_ALIAS,
        type: docType,
        body: scoresQueryBody.toJSON()
    });
```
`score.js` is using pseudo async await code using generators, yield and helper function which propagates the function execution on resolving a promise. 
The call to `es_client.js` function is wrapped ina `try catch` as follows:
```
module.exports = util.async(function* score(req, res, next) {
    try {
        // Some code setting up variables
        const esSurveyDetails = yield esClient.surveyDetails(projectId, docType, queryParams);
        // code processing the elasticsearch response and calling `res.send()` and `next`
    } catch (error) {
        req.log.error(error);
        return next(error);
    }
}
``` 
So answering your question, it is propagated using next().

**Comment by micahr** [comment]
Couple of questions @suhas-karanth: 

Are you transpiling your code and if so, what does the transpiled code look like? Second, what version of Node are you using?

I ask, because without knowing what the resulting code looks like, it is difficult to tell you how your errors are getting handled. I don't believe [Node currently](http://node.green/#async-functions) (as of writing this) has support in any version for async/await. Therefore, you are likely transpiling your code, which means that it gets turned into something different than what you pasted here. If there is indeed a promise involved, then a `try`/`catch` won't work in this context because of the asynchronous nature of the code. Instead, you should either use promises and put an error handler on the promise or use callbacks.

**Comment by suhas-karanth** [comment]
Okay, first off, I probably should have noticed this sooner. But formatter is failing because I am calling `req.query.hasOwnProperty('pretty')` again in the json formatter! This is because of issue #1168 due to old version of `qs` module(fixed in `restify-plugins` modue).

@micahr 
I will answer your questions anyway. I am not using any transpilers. I am using node v 6.4. You are right about node not having support for async/await. That is what I meant by pseudo async/await. I am using this helper function for achieving the effect:
```
# util.js
exports.async = function async(makeGenerator) {
    return function asyncFunc(...args) {
        const generator = makeGenerator(...args);

        function handle(result) {
            // result => { done: [Boolean], value: [Object] }
            if (result.done) {
                return Promise.resolve(result.value);
            }

            return Promise.resolve(result.value)
                .then((res) => {
                    return handle(generator.next(res));
                }).catch((err) => {
                    return handle(generator.throw(err));
                });
        }

        try {
            return handle(generator.next());
        } catch (ex) {
            return Promise.reject(ex);
        }
    };
};

# Then wrap our generator function with util.async
```
Credits: https://www.promisejs.org/generators/ - scroll to bottom
Although I am not really sure about the merits or benefits, you could also use standard implementation like [bluebird's coroutine](http://bluebirdjs.com/docs/api/promise.coroutine.html), [Q's spawn](https://github.com/kriskowal/q/wiki/API-Reference#qspawngeneratorfunction) or [co](https://github.com/tj/co)

**Comment by micahr** [comment]
Thanks for the update @suhas-karanth. 

Just to follow up further, the code you posted that wraps your async helper with `try`/`catch` will not properly pass the error object to `next`.

**Comment by suhas-karanth** [comment]
@micahr 

I have simulated an error scenario by not starting my elasticsearch instance. The code looks something like this:
```javascript
module.exports = util.async(function* score(req, res, next) {
    try {
        // Some code setting up variables
        const esSurveyDetails = yield esClient.surveyDetails(projectId, docType, queryParams);
        // code processing the elasticsearch response and calling `res.send()` and `next`
    } catch (error) {
        debug('Caught error in score try-catch');
        debug('error %j', error);
        req.log.error(error);
        return next(error);
    }
}
``` 

Response:
HTTP Status code: 500
```json
{
  "message": "No Living connections"
}
```

<details>
 <summary>Logs (slightly massaged):</summary>
```
// -> bunyan application logs(from elasticsearch)
WARN: Unable to revive connection: http://localhost:9200/
WARN: No living connections
// -> debug logs
  http_api:score Caught error in score try-catch +14ms
  http_api:score error {"message":"No Living connections"} +0ms
// -> bunyan req.log logs
ERROR: : No Living connections (req_id=47e08c3f-c07a-4bef-89af-b1a49d24c039)
    Error: No Living connections
        at sendReqWithConnection (/home/suhas/workspace/boolean_http_api/node_modules/elasticsearch/src/lib/transport.js:207:15)
        at next (/home/suhas/workspace/boolean_http_api/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)
        at _combinedTickCallback (internal/process/next_tick.js:67:7)
        at process._tickDomainCallback (internal/process/next_tick.js:122:9)
// -> audit logs
INFO: handled: 500 (req_id=47e08c3f-c07a-4bef-89af-b1a49d24c039, audit=true, remoteAddress=::ffff:127.0.0.1, remotePort=37818, latency=70, _audit=true, req.version=*)
    GET /v1/score?start_date=2016-06-16&end_date=2016-08-17&interval=month HTTP/1.1
    host: localhost:3000
    connection: keep-alive
    authorization: Basic dGVzdDo=
    cache-control: no-cache
    user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
    accept: */*
    accept-encoding: gzip, deflate, sdch
    accept-language: en-US,en;q=0.8
    --
    HTTP/1.1 500 Internal Server Error
    x-ratelimit-limit: 5000
    x-ratelimit-remaining: 4999
    x-ratelimit-reset: 1471926600000
    content-encoding: gzip
    content-type: application/json
    --
    Error: No Living connections
        at sendReqWithConnection (/home/suhas/workspace/boolean_http_api/node_modules/elasticsearch/src/lib/transport.js:207:15)
        at next (/home/suhas/workspace/boolean_http_api/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)
        at _combinedTickCallback (internal/process/next_tick.js:67:7)
        at process._tickDomainCallback (internal/process/next_tick.js:122:9)
    --
    req.query: {
      "start_date": "2016-06-16",
      "end_date": "2016-08-17",
      "interval": "month"
    }
    --
    req.timers: {
      "handler-0": 259,
      "checkUserAgent": 119,
      "rejectNonJSON": 174,
      "parseAccept": 6973,
      "asyncFunc": 40054,
      "authTimer": 170,
      "parseAuthorization": 647,
      "parseQueryString": 1940,
      "readBody": 406,
      "parseBody": 141,
      "gzip": 2923,
      "bunyan": 328
    }
```
</details>

As you can see from the debug logs, the error is indeed being caught by the catch block. I hope that clears it up.

**Comment by micahr** [comment]
Great, glad to see that yield is working as expected in this case!
