### ISSUE TITLE
Startup Error Messages

### ISSUE THREAD

**Issue by johannesgiani** [restify/node-restify#1284]
The following errors appear on startup:

{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Johannes/Documents/WebHtml/samplib-mysql-rest/node_modules/bunyan/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Johannes/Documents/WebHtml/samplib-mysql-rest/node_modules/bunyan/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Johannes/Documents/WebHtml/samplib-mysql-rest/node_modules/bunyan/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Johannes/Documents/WebHtml/samplib-mysql-rest/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Johannes/Documents/WebHtml/samplib-mysql-rest/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Johannes/Documents/WebHtml/samplib-mysql-rest/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }

SYSTEM:
Node v7.5.0
npm 4.1.2
macOS 10.12.3

**Comment by DonutEspresso** [comment]
Hello, can you please provide:

* output of `npms ls restify`
* output of `npm ls drace-provider`

This would help the debug process.

**Comment by batwicket** [comment]
perhaps this helps.. I am seeing similar issue. Restify and Bunyan are using different versions of dtrace-provider.

jf@box:/test$ npm ls restify
test@1.0.0 /test
└── restify@4.3.0

jf@box:/test$ npm ls dtrace-provider
test@1.0.0 /test
└─┬ restify@4.3.0
  ├─┬ bunyan@1.8.10
  │ └── dtrace-provider@0.8.1
  └── dtrace-provider@0.6.0

**Comment by retrohacker** [comment]
Closing this in favor of #1305

If I'm missing a nuance this issue provides, please call me out on it and we can either re-open this or copy over relevant details :heart:

**Comment by paprikka** [comment]
@batwicket Not sure if related, but I experienced the same issue when running integration tests on my api with `jest`/`superagent` + TypeScript.

`DTraceProviderBindings` file extension is `*.node`, hence the processor couldn't find it. I fixed it by updating my test config:

```js

// File: jest.config.integration.json
{
    "globals": {
        "ts-jest": {
            "tsConfigFile": "tsconfig.json"
        }
    },
    "moduleFileExtensions": [
        "ts",
        "js",
        "node" // look ma' I'm here!
    ],
    "transform": {
        "\\.(js|ts)$": "<rootDir>/node_modules/ts-jest/preprocessor.js"
    },
    "testMatch": [
        "**/test/integration/**/*.spec.(ts|js)"
    ],
    "forceExit": true,
    "testEnvironment": "node"
}
```
