### ISSUE TITLE
Node-Restify 4.3 - Error when no uri is given when creating a http_client and no_proxy environment variable is present

### ISSUE THREAD

**Issue by Crazedpeanut** [restify/node-restify#1296]
Node-Restify 4.3 - Error when no uri is given when creating a http_client and no_proxy environment variable is present

TypeError: Cannot read property 'replace' of null
      at isProxyForURL (node_modules/restify/lib/clients/http_client.js:287:36)
      at JsonClient.HttpClient (node_modules/restify/lib/clients/http_client.js:376:24)
      at JsonClient.StringClient (node_modules/restify/lib/clients/string_client.js:29:16)
      at new JsonClient (node_modules/restify/lib/clients/json_client.js:23:18)
      at createClient (node_modules/restify/lib/index.js:46:22)
      at Object.createJsonClient (node_modules/restify/lib/index.js:79:13)
      at PromiseInvoker.invoke (src/promise-invoker.js:9:3786)
      at Context.it (test/promise-invoker.unit.test.js:256:30)

**Comment by retrohacker** [comment]
I'm closing this as stale for now due to inactivity on #1297 

We can re-open and discuss if we get a repro case :smile:
