### ISSUE TITLE
TravisCI breaks with EADDRNOTAVAIL

### ISSUE THREAD

**Issue by hekike** [restify/node-restify#1545]
# Bug Report

`master` tests pass on a local machine but break on TravisCI:

**server.test.js / gh-751 IPv4/IPv6 server URL**

```
Error: listen EADDRNOTAVAIL ::1:36480
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1249:19)
    at listen (net.js:1298:10)
    at net.js:1408:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

## Node.js Version

all

## Repro case

See: https://travis-ci.org/restify/node-restify/jobs/295430142

## Are you willing and able to fix this?

Yes, but I need a hint

**Comment by hekike** [comment]
Seems to be that the current version of TravisCI lacks the IPv6 support:

> The virtual machines in the Legacy environment running the tests have IPv6 enabled. They do not have any external IPv4 address but are fully able to communicate with any external IPv4 service. The container-based, OS X, and GCE (both Precise and Trusty) builds do not currently have IPv6 connectivity. - https://docs.travis-ci.com/user/reference/precise/#Networking

I'm not sure why we have this issue now.
