### ISSUE TITLE
TypeError: path must be a string or Buffer with multipart form data and 'multiples'

### ISSUE THREAD

**Issue by stilllife00** [restify/node-restify#1624]
- [X] Used appropriate template for the issue type
- [X] Searched both open and closed issues for duplicates of this issue
- [X] Title adequately and _concisely_ reflects the feature or the bug

# Bug Report
## Restify Version 
6.3.4

## Node.js Version
8.5.0

## Expected behaviour
Should work without crashing

## Actual behaviour

Sending to restify a multipart form data containing multiple files (<input type="file" multiple name="files[]">), when setting in the body parser the option `"multiples": true` without setting a `multipartFileHandler` (because I prefer to have the files in the params) the app crashes with an error:

````
fs.js:359
  binding.open(pathModule._makeLong(path),
          ^

TypeError: path must be a string or Buffer
    at Object.fs.readFile (fs.js:359:11)
    at forEach (####/node_modules/restify/lib/plugins/multipartBodyParser.js:115:28)
    at Array.forEach (<anonymous>)
    at parse (####/node_modules/restify/lib/plugins/multipartBodyParser.js:110:40)
    at IncomingForm.<anonymous> (####/node_modules/formidable/lib/incoming_form.js:105:9)
    at emitNone (events.js:105:13)
    at IncomingForm.emit (events.js:207:7)
    at IncomingForm._maybeEnd (####/node_modules/formidable/lib/incoming_form.js:553:8)
    at /Users/mirko/Sites/valifly-api/node_modules/formidable/lib/incoming_form.js:230:12
    at WriteStream.<anonymous> (####/node_modules/formidable/lib/file.js:74:5)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at WriteStream.emit (events.js:207:7)
    at finishMaybe (_stream_writable.js:603:14)
    at afterWrite (_stream_writable.js:455:3)
    at onwrite (_stream_writable.js:445:7)
````
Note that it works fine with only 1 file and it also works if setting the custom callback `multipartFileHandler`

## Repro case
Client side: a normal form with input file multiple
Request sent as multipart form data, boundaries automatically set by Chrome

Server
````
    server.use(restify.plugins.bodyParser({
        mapParams: true,
        mapFiles: true,
        multiples: true,
        maxBodySize: 0,
        uploadDir: 'uploads',
        //multipartFileHandler: () => {}
    }));

    server.post('/run', run);
````

## Cause
No idea but the logs should help

## Are you willing and able to fix this?
Not sure, if you confirm that it is a bug I can take a look

**Comment by DonutEspresso** [comment]
Apologies - not sure how I missed this issue! @stilllife00 any chance you can put together a repro case using a node based client? That'd help us get to the root of this much more quickly!
