### ISSUE TITLE
Versioned Routes example code does not work.

### ISSUE THREAD

**Issue by dogenius01** [restify/node-restify#1641]
#Source Code
http://restify.com/docs/home/

var restify = require('restify');

var server = restify.createServer();

function sendV1(req, res, next) {
  res.send('hello: ' + req.params.name);
  return next();
}

function sendV2(req, res, next) {
  res.send({hello: req.params.name});
  return next();
}

var PATH = '/hello/:name';
server.get({path: PATH, version: '1.1.3'}, sendV1);
server.get({path: PATH, version: '2.0.0'}, sendV2);

server.listen(8080);

# Bug Report
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Method 'GET' already declared for route '/hello/:'
    at Router._insert (/usr/local/globalcdn/zonemaker/node_modules/find-my-way/index.js:208:7)
    at Router._on (/usr/local/globalcdn/zonemaker/node_modules/find-my-way/index.js:120:21)
    at Router.on (/usr/local/globalcdn/zonemaker/node_modules/find-my-way/index.js:47:8)
    at RouterRegistryRadix.add (/usr/local/globalcdn/zonemaker/node_modules/restify/lib/routerRegistryRadix.js:42:21)
    at Router.mount (/usr/local/globalcdn/zonemaker/node_modules/restify/lib/router.js:167:20)
    at Server.serverMethod [as get] (/usr/local/globalcdn/zonemaker/node_modules/restify/lib/server.js:1476:33)
    at Object.<anonymous> (/usr/local/globalcdn/zonemaker/app.js:17:8)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)

## Restify Version
v7.1.0
## Node.js Version
v8.8.1

**Comment by hekike** [comment]
Fix: https://github.com/restify/node-restify/pull/1642

**Comment by hekike** [comment]
Released as: `v7.1.1`, thanks for reporting this!

**Comment by hekike** [comment]
Please check out the updated example code.

**Comment by dogenius01** [comment]
@hekike 
Thank you.
But, the example code in http://restify.com/docs/home/ is still same.
However, i found updated one from https://github.com/restify/node-restify/pull/1642/files/fa7c70637f6deddeeea7903d2756fc712e435df5.

Please, update the document for other people. :)
Thank you again.

**Comment by hekike** [comment]
Thanks, website updated!

**Comment by talatm02** [comment]
Same error in Restify V: 7.6.0
