### ISSUE TITLE
Restify crashes at the end of a request (returns the request correctly)

### ISSUE THREAD

**Issue by frbuceta** [restify/node-restify#1646]
# Bug Report

## Restify Version
7.1.1

## Node.js Version
9.11.1

## Expected behaviour

> Send string via json

## Actual behaviour

> Restify I execute my code perfectly, but when the request ends ... Restify crash

## Repro case

routes/index.js (Use restify-router-magic as router)
```
module.exports = (server, path, options) => {
    return {
        get: (req, res, next) => {
            return next(res.send('hey'))
        }
    }
};
```

Console Log
```
/home/fran/Projects/xxxxxxxxxx-xxxx/node_modules/restify/lib/server.js:1440
        return err.name.replace(/Error$/, '');
                        ^

TypeError: Cannot read property 'replace' of undefined
    at errEvtNameFromError (/home/fran/Projects/xxxxxxxxxx-xxxx/node_modules/restify/lib/server.js:1440:25)
    at Server._emitErrorEvents (/home/fran/Projects/xxxxxxxxxx-xxxx/node_modules/restify/lib/server.js:1279:19)
    at Server._routeErrorResponse (/home/fran/Projects/xxxxxxxxxx-xxxx/node_modules/restify/lib/server.js:1239:10)
    at Server._onHandlerError (/home/fran/Projects/xxxxxxxxxx-xxxx/node_modules/restify/lib/server.js:1074:10)
    at Server._afterRoute (/home/fran/Projects/xxxxxxxxxx-xxxx/node_modules/restify/lib/server.js:947:14)
    at Immediate.afterRouter (/home/fran/Projects/xxxxxxxxxx-xxxx/node_modules/restify/lib/server.js:923:18)
    at runCallback (timers.js:764:11)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:102:23)
[nodemon] app crashed - waiting for file changes before starting...
```

## Are you willing and able to fix this?

No, I really do not know why it's happening.

**Comment by frbuceta** [comment]
@fidian has found the bug in the code. in [tests-always-included/restify-router-magic#5](https://github.com/tests-always-included/restify-router-magic/issues/5)

Close issue
