### ISSUE TITLE
Starting in v6.3.0 example dtrace script crashes node

### ISSUE THREAD

**Issue by Smithx10** [restify/node-restify#1649]
starting application: 
```
[root@frr-sos ~/rest-fibo/fibo/src]# node api.js
{"name":"fibo-api","hostname":"frr-sos","pid":631692,"app_type":"fibo-restify","level":30,"msg":"ready on http://[::]:8080","time":"2018-04-24T03:38:52.447Z","v":0}
```

instrument system with [this](https://raw.githubusercontent.com/restify/node-restify/master/examples/dtrace/handler-timing.d) dtrace script:
```
[root@frr-sos ~/rest-fibo/fibo/src]# dtrace -s latency.d
dtrace: script 'latency.d' matched 4 probes
```

hit an endpoint
```
[root@frr-sos ~]# curl 127.0.0.1:8080/api/fibo/4
curl: (52) Empty reply from server
```

node throws:
```
/root/rest-fibo/fibo/src/node_modules/restify/lib/server.js:1100
                res.headers()
                    ^

TypeError: res.headers is not a function
    at DTraceProbe.fire (/root/rest-fibo/fibo/src/node_modules/restify/lib/server.js:1100:21)
    at next (/root/rest-fibo/fibo/src/node_modules/restify/lib/server.js:1094:44)
    at f (/root/rest-fibo/fibo/src/node_modules/once/once.js:36:25)
    at Server.<anonymous> (/root/rest-fibo/fibo/src/api.js:45:5)
    at next (/root/rest-fibo/fibo/src/node_modules/restify/lib/server.js:1089:29)
    at f (/root/rest-fibo/fibo/src/node_modules/once/once.js:36:25)
    at Server._run (/root/rest-fibo/fibo/src/node_modules/restify/lib/server.js:1143:16)
    at Server._handle (/root/rest-fibo/fibo/src/node_modules/restify/lib/server.js:836:14)
    at Server.onRequest (/root/rest-fibo/fibo/src/node_modules/restify/lib/server.js:211:14)
    at emitTwo (events.js:125:13)
[root@frr-sos ~/rest-fibo/fibo/src]#
****
```

**Comment by hekike** [comment]
Fixed by: https://github.com/restify/node-restify/issues/1648

**Comment by hekike** [comment]
Thanks for reporting!
