### ISSUE TITLE
chai and restify

### ISSUE THREAD

**Issue by rohityadav-agilets** [restify/node-restify#1657]
# Bug Report
Using restify with chai throws an error

## Restify Version
7.1.1
## Node.js Version
8.11.1
## Expected behaviour

should create a client and pass it to chai

## Actual behaviour
```
app.address is not a function
      at serverAddress (node_modules/chai-http/lib/request.js:276:18)
      at new Test (node_modules/chai-http/lib/request.js:265:53)
      at Object.obj.(anonymous function) [as get] (node_modules/chai-http/lib/request.js:235:14)
      at Context.<anonymous> (test/epserviceTest.js:29:7)
```
## Repro case

```
const clients = require('restify-clients');
const client = clients.createJsonClient({
	  url: 'http://localhost:9090',
	  version: '*'
	});

const chai = require("chai");
const expect = chai.expect;

chai.use(require("chai-http"));

describe('/GET passes as expected', () => {
	it("should check for grace period", function (done) {
	    chai.request(client)
	    .get('/test/value/1')
	    .end((err, res) => {
	    	let myObj = {"test":0};
	    	expect(res).to.have.status(200);
	    	expect(res).to.be.json;
	    	expect(res).to.have.header('content-type', 'application/json; charset=utf-8');
	    	expect(err).to.be.null;
	    	expect(res.body).to.be.eql(myObj);
	    	done();
	    });
	});
});
```

**Comment by DonutEspresso** [comment]
I'm not super familiar with chai-http, but it looks like `chai.request` should take an http server and not a client as in y our repro case?

**Comment by DonutEspresso** [comment]
Thanks - your repro case is passing a client into `chai.request` though - am I missing something?

**Comment by rohityadav-agilets** [comment]
No. I was wrong and the issue is not with restify. Basically, i had to pass an http server and not a client. I am closing the issue.

**Comment by DonutEspresso** [comment]
Great, thank you!
