### ISSUE TITLE
throw err; // Rethrow non-MySQL errors

### ISSUE THREAD

**Issue by sugizo** [restify/node-restify#1664]
## Expected behaviour
same code run smoothly in node version 8.9 (using curl or access via browser), after upgrade nodejs to 8.11.2, the server run, but when request from browser, it return the data after that thrown an error
not sure how to check restify version (confuse with the changelog.md and changes.md), error occured after upgrade nodejs

## Actual behaviour
$ /Applications/AMPPS/mysql/bin/mysqld &

$ node -v
v8.11.2

$ npm start

> api@0.0.0 start /Users/sugizo/Downloads/learn/test
> node main.js

test listening at http://[::]:3001
/Users/sugizo/Downloads/learn/test/node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

Error: ER_NO_SUCH_TABLE: Table 'favicon.ico' doesn't exist
    at Query.Sequence._packetToError (/Users/sugizo/Downloads/learn/test/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/sugizo/Downloads/learn/test/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/sugizo/Downloads/learn/test/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/sugizo/Downloads/learn/test/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/sugizo/Downloads/learn/test/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/sugizo/Downloads/learn/test/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (/Users/sugizo/Downloads/learn/test/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Connection.query (/Users/sugizo/Downloads/learn/test/node_modules/mysql/lib/Connection.js:208:25)
    at /Users/sugizo/Downloads/learn/test/main.js:26:16
    at call (/Users/sugizo/Downloads/learn/test/node_modules/restify/lib/chain.js:164:9)
    at next (/Users/sugizo/Downloads/learn/test/node_modules/restify/lib/chain.js:120:9)
    at Chain.run (/Users/sugizo/Downloads/learn/test/node_modules/restify/lib/chain.js:123:5)
    at onRoute (/Users/sugizo/Downloads/learn/test/node_modules/restify/lib/routerRegistryRadix.js:46:25)
    at afterUse (/Users/sugizo/Downloads/learn/test/node_modules/restify/lib/server.js:932:9)
    at Server._afterUse (/Users/sugizo/Downloads/learn/test/node_modules/restify/lib/server.js:1038:5)
    at Immediate.useChainDone [as _onImmediate] (/Users/sugizo/Downloads/learn/test/node_modules/restify/lib/server.js:1005:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api@0.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the api@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sugizo/.npm/_logs/2018-05-22T07_09_56_342Z-debug.log

$ cat /Users/sugizo/.npm/_logs/2018-05-22T07_09_56_342Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle api@0.0.0~prestart: api@0.0.0
6 info lifecycle api@0.0.0~start: api@0.0.0
7 verbose lifecycle api@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle api@0.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/sugizo/Downloads/learn/test/node_modules/.bin:/Users/sugizo/miniconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
9 verbose lifecycle api@0.0.0~start: CWD: /Users/sugizo/Downloads/learn/test
10 silly lifecycle api@0.0.0~start: Args: [ '-c', 'node main.js' ]
11 silly lifecycle api@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle api@0.0.0~start: Failed to exec start script
13 verbose stack Error: api@0.0.0 start: `node main.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid api@0.0.0
15 verbose cwd /Users/sugizo/Downloads/learn/test
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.11.2
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error api@0.0.0 start: `node main.js`
22 error Exit status 1
23 error Failed at the api@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by DonutEspresso** [comment]
@sugizo this doesn't look like a restify problem - am I missing something?

**Comment by rodrigooler** [comment]
@sugizo by the stacktrace points that it is problem in "node_modules/mysql/" ... and apparently not in restify, I advise you to open an issue here https://github.com/mysqljs/mysql

**Comment by rodrigooler** [comment]
@sugizo could you solve the above problem?

**Comment by sugizo** [comment]
solved by

```
$ mkdir -p public/images
$ npm install serve-favicon --save
```

put favicon.ico in public/images folder

and modified main.js

```
const favicon = require('serve-favicon');
const path = require('path');
server.use(favicon(path.join(__dirname, 'public', 'images', 'favicon.ico') ) );
```

please change public/images (default expressjs path) with your desired path to store favicon.ico

**Comment by rodrigooler** [comment]
Very good @sugizo , I think it would be better if you changed the name of the issue to "`Error: ER_NO_SUCH_TABLE: Table 'favicon.ico' doesn't exist`", I believe it will help people in the future find it if they have the same problem.
