### ISSUE TITLE
metrics.test.js seems to be flaky

### ISSUE THREAD

**Issue by misterdjules** [restify/node-restify#1691]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

# Bug Report

## Restify Version

v7.2.1, from commit e663699c8c5383eb6affad16ac2eb14fcd66a858 in master branch.

## Node.js Version

Various Node.js versions, including 4.x, 6.x up to 10.x.

## Expected behaviour

Tests in `metrics.test.js` should consistently pass.

## Actual behaviour

Tests in `metrics.test.js` sometimes fail with the following error:

```
/home/travis/build/restify/node-restify/node_modules/chai/lib/chai/interface/assert.js:2895
      throw(val);
      ^
AssertionError: expected 49 to be at least 50
    at /home/travis/build/restify/node-restify/test/plugins/metrics.test.js:206:28
    at Server.metrics (/home/travis/build/restify/node-restify/lib/plugins/metrics.js:92:16)
    at emitMany (events.js:108:13)
    at Server.emit (events.js:182:7)
    at Server._finishReqResCycle (/home/travis/build/restify/node-restify/lib/server.js:1241:14)
    at Server._afterRoute (/home/travis/build/restify/node-restify/lib/server.js:979:10)
    at Immediate.afterRouter (/home/travis/build/restify/node-restify/lib/server.js:949:18)
    at Immediate.immediate._onImmediate (timers.js:458:18)
    at processImmediate [as _immediateCallback] (timers.js:396:17)
make: *** [test] Error 7
```

See https://travis-ci.org/restify/node-restify/jobs/411481436 for an example.

## Repro case

The `metrics.test.js` tests suite fails sporadically in the Travis environment. It is not clear to me yet whether this is reproducible in another environment. The nature of the environment in which the tests suite runs is relevant here, as the presence or absence of a virtualization layer may have an impact on the timing facilities of the Node.js runtime, and may have an impact on the behavior of this tests suite.

## Cause

From a quick look at it it seems it could be due to either (this list is not exhaustive):

1) an issue with node timers that _sometimes_ fire 1ms earlier than specified.
2) an issue with the `process.hrtime` implementation that sometimes round up to the nearest milisecond.

## Are you willing and able to fix this?

Yes. Some thoughts on how to fix this:

1. Investigate timers/`process.hrtime`'s behavior and fix any erroneous behavior that might be identified.
2. Use something like `assert.closeTo` instead of `assert.isAtLeast` to relax the test so that it doesn't fail when the actual value is very close but less than the expected value (suggested by @DonutEspresso ).

**Comment by misterdjules** [comment]
As a first step, I'd suggesting trying to reproduce the problem locally (on a non-virtualized platform, like a laptop) by running that specific tests suite in a loop until it fails. If not reproducible locally, it might be an indication that something specific to the TravisCI environment is contributing to this behavior.

**Comment by misterdjules** [comment]
Landed in https://github.com/restify/node-restify/commit/11d6458824d69493b0ddec080c55e57ca40730ef, thanks @michaelnisi!
