### ISSUE TITLE
static.test.js tests suite is flaky

### ISSUE THREAD

**Issue by misterdjules** [restify/node-restify#1726]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

# Bug Report

## Restify Version

7.3.0

## Node.js Version

8.12.0

## Expected behaviour

`static.test.js` should pass all the time.

## Actual behaviour

`static.test.js` fails sometimes when running that test locally or when it's run by TravisCI.

## Repro case

```
$ (latest_exit_code=0; while [ $latest_exit_code -eq 0 ]; do ./node_modules/.bin/mocha test/plugins/static.test.js; latest_exit_code=$?; done)
```

The sub-shell will exit after a few dozens or hundreds runs and error with:

```
 static resource plugin
    ✓ static serves static files
    ✓ static serves static files in nested folders
    ✓ static serves static files in with a root regex
    ✓ static serves static files with a root, !greedy, regex
    ✓ static serves default file
    ✓ restify-GH-379 static serves file with parentheses in path
    ✓ restify-GH-719 serve a specific static file
    ✓ static serves static file with appendRequestPath = false
    ✓ static serves default file with appendRequestPath = false
    ✓ restify serve a specific static file with appendRequestPath = false
    ✓ static responds 404 for missing file
    ✓ GH-1382 static responds 404 for missing file with percent-codes
    ✓ static does not leak the file stream and next() is properly called when the client disconnects before receiving a reply
    1) static does not open a file stream and next() is properly called when the client disconnects immediately after sending a request
    ✓ static responds 404 for missing file
    ✓ GH-1382 static responds 404 for missing file with percent-codes


  15 passing (132ms)
  1 failing

  1) static resource plugin static does not open a file stream and next() is properly called when the client disconnects immediately after sending a request:
     Uncaught AssertionError: Unspecified AssertionError
      at Object.fs.createReadStream (test/plugins/static.test.js:344:17)
      at serveFileFromStats (lib/plugins/static.js:113:26)
      at fileStat (lib/plugins/static.js:159:17)
      at FSReqWrap.oncomplete (fs.js:153:5)
```

## Cause

I don't know the cause.

## Are you willing and able to fix this?

Yes.

**Comment by misterdjules** [comment]
Closing because for some reason I cannot reproduce this issue anymore. I'm not sure if it's because it occurs very rarely and I was lucky to stumble on it when I reported the issue, or because my initial repro was relying on something that is not happening anymore.

Will reopen if I manage to reproduce it later.
