### ISSUE TITLE
bodyReader does not work with both gunzip and maxBodySize

### ISSUE THREAD

**Issue by jfilipczyk** [restify/node-restify#1785]
# Bug Report
`bodyReader` plugin setup with `maxBodySize` when called with `Content-Encoding: gzip` with body size over the body limit causes zlib buffer error and eventually stops process. 

## Restify Version
8.3.2

## Node.js Version
10.14.2

## Expected behaviour

Return "413 Body Too Long". Same behaviour as for not gzipped content. 

## Actual behaviour

server is down with error:

```bash
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:154:17)
Emitted 'error' event at:
    at Zlib.zlibOnError [as onerror] (zlib.js:157:8)
```

## Repro case

```js
'use strict';

const restify = require('restify');
const got = require('got');
const zlib = require('zlib');

const payload = { apple: 'red' };
const body = zlib.gzipSync(JSON.stringify(payload));

// set maxBodySize smaller than gzipped body
const maxBodySize = body.byteLength - 1;

const server = restify.createServer();
server.listen(3000, '127.0.0.1');
server.use(restify.plugins.bodyParser({ maxBodySize }));
server.post('/foo', (req, res, next) => {
    res.send();
    next();
});

got({
    url: 'http://127.0.0.1:3000/foo',
    body,
    json: false,
    throwHttpErrors: false,
    headers: {
        'Content-Encoding': 'gzip',
        'Content-Type': 'application/json'
    }
})
    .then(response => console.log(response.statusCode))
    .catch(err => console.log(err));
```

## Cause

bodyReader `done` handler function is not triggered when gunzip transformer emits error due to incomplete buffer when it is incomplete because maxBodySize limit was reached.

## Are you willing and able to fix this?

Yes. PR is on the way.

**Comment by wraithgar** [comment]
The `request` package had a similar bug (no-body gunzip) and it was fixed in https://github.com/request/request/pull/2176
