### ISSUE TITLE
Update to latest assert-plus

### ISSUE THREAD

**Issue by cavis** [restify/node-restify#966]
Similar to restify/errors#15 ... I'm unable to run a restify server in strict mode.  Seems like upgrading to the latest `assert-plus` would fix this.

```
node --use_strict index.js
~/code/restify-test/node_modules/restify/node_modules/assert-plus/assert.js:41
                stackFunc = stackFunc || _assert.caller;
                                                ^

TypeError: 'caller' and 'arguments' are restricted function properties and cannot be accessed in this context.
    at _assert (~/code/restify-test/node_modules/restify/node_modules/assert-plus/assert.js:41:49)
    at Object.object (~/code/restify-test/node_modules/restify/node_modules/assert-plus/assert.js:141:9)
    at new RequestCaptureStream (~/code/restify-test/node_modules/restify/lib/bunyan_helper.js:70:12)
    at Object.createLogger (~/code/restify-test/node_modules/restify/lib/bunyan_helper.js:276:25)
    at Object.createServer (~/code/restify-test/node_modules/restify/lib/index.js:140:35)
    at Object.<anonymous> (~/code/restify-test/index.js:3:22)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

**Comment by cavis** [comment]
Thanks!  I think you also need to update your `restify-errors` dependency to `3.1.0` - otherwise it pulls in the old `assert-plus` module, and running a restify server fails with a similar error.

```
node --use_strict index.js
~/code/restify-test/node_modules/restify/node_modules/restify-errors/node_modules/assert-plus/assert.js:41
                stackFunc = stackFunc || _assert.caller;
                                                ^

TypeError: 'caller' and 'arguments' are restricted function properties and cannot be accessed in this context.
```
