### ISSUE TITLE
Error when run examples/todoapp

### ISSUE THREAD

**Issue by shuangshan** [restify/node-restify#975]
node main.js 2>&1 | bunyan it has errors:
util.js:634
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:634:43)
    at Object.<anonymous> (/home/shuangshan/grommet/example/node-restify/examples/todoapp/lib/server.js:24:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/shuangshan/grommet/example/node-restify/examples/todoapp/lib/index.js:5:19)
    at Module._compile (module.js:460:26)

**Comment by micahr** [comment]
It looks like the issue is due to the construction of Errors changing. Thank you for letting us know!
